### ISSUE TITLE
Can you share the complete code? Missing param file

### ISSUE THREAD

**Issue by darlingbenke** [eliasgoldsztejn95/Bridging-the-Gap#1]
Can you share the complete code? Missing param file

**Comment by eliasgoldsztejn95** [comment]
The param file is task_params.yaml, you can find it in the Training folder.

**Comment by darlingbenke** [comment]
I have used the file you mentioned, but it is still missing parameters. I'm very interested in it，and if you could help me, I would be very grateful to you.

WARNING: cannot load logging configuration file, logging is disabled
---------------------------------------
Policy: TD3, Env: PTDRL, Seed: 0
---------------------------------------
Traceback (most recent call last):
  File "/home/rl/Bridging-the-Gap-main/Training/train.py", line 216, in <module>
    main()
  File "/home/rl/Bridging-the-Gap-main/Training/train.py", line 103, in main
    env = task_env.PtdrlTaskEnv()
  File "/home/rl/Bridging-the-Gap-main/Training/task_env.py", line 80, in __init__
    self.get_params()
  File "/home/rl/Bridging-the-Gap-main/Training/task_env.py", line 157, in get_params
    for i in range(len(data[0][tune_params])):
KeyError: 'tune_params_dwa'

Process finished with exit code 1

**Comment by eliasgoldsztejn95** [comment]
Sorry, the task_params.yaml file that it is expecting was from a previous paper: PTDRL: https://github.com/eliasgoldsztejn95/PTDRL/blob/main/ptdrl/params/task_params.yaml

I will update it here as well.

**Comment by darlingbenke** [comment]
I am very disappointed, there are still issues.
  File "/home/rl/cmu_ws/large_scale_exploration_ros/Bridging-the-Gap-main/Training/task_env.py", line 80, in __init__
    self.get_params()
  File "/home/rl/cmu_ws/large_scale_exploration_ros/Bridging-the-Gap-main/Training/task_env.py", line 157, in get_params
    for i in range(len(data[0][tune_params])):
KeyError: 'tune_params_dwa'

**Comment by eliasgoldsztejn95** [comment]
contact me at my email: eliasgol@post.bgu.ac.il
